### ISSUE TITLE
Unlock charge port

### ISSUE THREAD

**Issue by doubledrat** [tdorssers/TeslaPy#106]
I have an app which can send a command to unlock the charge port on my tesla, but can't seem to do it with teslapy.  Am I missing something, or is there perhaps a new command available that is not currently available in teslapy?

**Comment by tdorssers** [comment]
'CHARGE_PORT_DOOR_OPEN' should unlock the charge port when its locked.

**Comment by doubledrat** [comment]
thanks :)
