### ISSUE TITLE
passing boolean value to API endpoint

### ISSUE THREAD

**Issue by ncstdc** [tdorssers/TeslaPy#18]
I am trying to use the API endpoint `STORM_MODE_SETTINGS` and it is expecting bool value.

Running `cli.py ... -a STORM_MODE_SETTINGS -k enabled=True`
gets this error
`requests.exceptions.HTTPError: 400 Client Error: https://powergate.prd.sn.tesla.services:443/api/v2/energy_site/storm_mode => Unable to read user settings payload --(Error)--> [[ json: cannot unmarshal string into Go struct field StormModeSettings.enabled of type bool ]] for url: https://owner-api.teslamotors.com/api/1/energy_sites/XXX/storm_mode`

Is there way to pass a boolean value?

Thanks

**Comment by tdorssers** [comment]
Hi, can you give the fix in a7d61f3 a try?

**Comment by ncstdc** [comment]
That works. Thanks
