### ISSUE TITLE
Setting passenger temperature results in  lowest setting.

### ISSUE THREAD

**Issue by johnypony3** [tdorssers/TeslaPy#74]
I'd like to thank you for this body of work. Very well crafted!

Setting the drivers temperature works as expected. Newest version 2.5.0

```json
{"name":"change_climate_temperature_setting","data":{"driver_temp":20.555555555555554},"result":true}

{"name":"change_climate_temperature_setting","data":{"passenger_temp":20.555555555555554},"result":true}
```

![image](https://user-images.githubusercontent.com/1817034/164908988-63a58860-f29c-4997-b8df-1298b17d359e.jpeg)

**Comment by tdorssers** [comment]
You need to pass both driver_temp and passenger_temp. Also both values should be equal.

cli.py -e elon@tesla.com -c CHANGE_CLIMATE_TEMPERATURE_SETTING -k driver_temp=20 -k passenger_temp=20

**Comment by johnypony3** [comment]
that definitely worked, any insight into why they have to be equal?
