### ISSUE TITLE
Can't get values

### ISSUE THREAD

**Issue by dawiinci** [tdorssers/TeslaPy#8]
```
import teslapy
with teslapy.Tesla(tesla_mail, tesla_pass) as tesla:
    tesla.fetch_token()
    vehicles = tesla.vehicle_list()
    vehicles[0].sync_wake_up()
    test = vehicles[0]['charge_state']['charging_state']
```

This should give me the charging state, but it doesn't. It doesn't work for any value. Commands work though and state returns "online":

```
vehicles[0].command('STOP_CHARGE')
vehicles[0]['state']
```

**Comment by tdorssers** [comment]
Please change the last line to:
`test = vehicles[0].get_vehicle_data()['charge_state']['charging_state']`

**Comment by dawiinci** [comment]
Thank you, that works perfectly.
